In [25]:
!pwd

/media/ntu/volume1/home/s122md306_05/Mask-ShadowGAN


In [1]:
# %cd Mask-ShadowGAN/


/media/ntu/volume1/home/s122md306_05/Mask-ShadowGAN


In [2]:
!pwd

/media/ntu/volume1/home/s122md306_05/Mask-ShadowGAN


In [5]:
!ls ../dataset

 ISTD_Dataset   ISTD_dataset.zip  'view?usp=sharing'


In [ ]:
!python3 train_Mask-ShadowGAN --n_epochs 200 --dataroot "../dataset/ISTD_Dataset" \
 --decay_epoch 100 --batchSize 1 --output_dir "../output_200_epoches"\
 --snapshot_epochs 20 2>&1 | tee ../epoches_200.log

/media/ntu/volume1/home/s122md306_05/Mask-ShadowGAN/train_Mask-ShadowGAN:141: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  transforms.Resize(int(opt.size * 1.12), Image.BICUBIC),
/media/ntu/volume1/home/s122md306_05/miniconda3/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
using GPU: 3
Namespace(epoch=0, n_epochs=200, batchSize=1, dataroot='../dataset/ISTD_Dataset', lr=0.0002, decay_epoch=100, size=400, input_nc=3, output_nc=3, cuda=True, n_cpu=8, snapshot_epochs=20, resume=False, iter_loss=500, data_len=9999, output_dir='../output_200_epoches', log_path='../output_200_epoches/2023-01-15 22:51:26.253207.txt')
  0%|          | 0/1330 [00:00<?, ?it/s]/media/ntu/volume1/home/s122md306_05/miniconda3/lib/python3.10/site-packages/torch/nn

 34%|███▍      | 450/1330 [03:11<05:52,  2.49it/s]

In [26]:
!python3 generate_output.py --dataroot "../dataset/ISTD_Dataset"\
--generated_dir "../generated_200_epoches"\
--generator_A2B "../output_200_epoches/netG_A2B.pth" \
2>&1 | tee "../gen_log"

/media/ntu/volume1/home/s122md306_05/Mask-ShadowGAN/generate_output.py:86: DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead.
  transforms.Resize((int(opt.size),int(opt.size)), Image.BICUBIC),
/media/ntu/volume1/home/s122md306_05/miniconda3/lib/python3.10/site-packages/torchvision/transforms/transforms.py:329: UserWarning: Argument 'interpolation' of type int is deprecated since 0.13 and will be removed in 0.15. Please use InterpolationMode enum.
  warnings.warn(
using GPU: 3
Namespace(batchSize=1, dataroot='../dataset/ISTD_Dataset', input_nc=3, output_nc=3, size=400, cuda=True, n_cpu=8, generator_A2B='../output_200_epoches/netG_A2B.pth', generator_B2A='output/netG_B2A.pth', generated_dir='../generated_200_epoches', dataroot_A='../dataset/ISTD_Dataset/test/test_A', dataroot_B='../dataset/ISTD_Dataset/test/test_C', im_suf_A='.png', im_suf_B='.png')
predicting: 1 / 540
Generated images 0001 of 0540
predicting: 2 / 540


predicting: 153 / 540
Generated images 0153 of 0540
predicting: 154 / 540
Generated images 0154 of 0540
predicting: 155 / 540
Generated images 0155 of 0540
predicting: 156 / 540
Generated images 0156 of 0540
predicting: 157 / 540
Generated images 0157 of 0540
predicting: 158 / 540
Generated images 0158 of 0540
predicting: 159 / 540
Generated images 0159 of 0540
predicting: 160 / 540
Generated images 0160 of 0540
predicting: 161 / 540
Generated images 0161 of 0540
predicting: 162 / 540
Generated images 0162 of 0540
predicting: 163 / 540
Generated images 0163 of 0540
predicting: 164 / 540
Generated images 0164 of 0540
predicting: 165 / 540
Generated images 0165 of 0540
predicting: 166 / 540
Generated images 0166 of 0540
predicting: 167 / 540
Generated images 0167 of 0540
predicting: 168 / 540
Generated images 0168 of 0540
predicting: 169 / 540
Generated images 0169 of 0540
predicting: 170 / 540
Generated images 0170 of 0540
predicting: 171 / 540
Generated images 0171 of 0540
predicting: 

Generated images 0310 of 0540
predicting: 311 / 540
Generated images 0311 of 0540
predicting: 312 / 540
Generated images 0312 of 0540
predicting: 313 / 540
Generated images 0313 of 0540
predicting: 314 / 540
Generated images 0314 of 0540
predicting: 315 / 540
Generated images 0315 of 0540
predicting: 316 / 540
Generated images 0316 of 0540
predicting: 317 / 540
Generated images 0317 of 0540
predicting: 318 / 540
Generated images 0318 of 0540
predicting: 319 / 540
Generated images 0319 of 0540
predicting: 320 / 540
Generated images 0320 of 0540
predicting: 321 / 540
Generated images 0321 of 0540
predicting: 322 / 540
Generated images 0322 of 0540
predicting: 323 / 540
Generated images 0323 of 0540
predicting: 324 / 540
Generated images 0324 of 0540
predicting: 325 / 540
Generated images 0325 of 0540
predicting: 326 / 540
Generated images 0326 of 0540
predicting: 327 / 540
Generated images 0327 of 0540
predicting: 328 / 540
Generated images 0328 of 0540
predicting: 329 / 540
Generated im

Generated images 0467 of 0540
predicting: 468 / 540
Generated images 0468 of 0540
predicting: 469 / 540
Generated images 0469 of 0540
predicting: 470 / 540
Generated images 0470 of 0540
predicting: 471 / 540
Generated images 0471 of 0540
predicting: 472 / 540
Generated images 0472 of 0540
predicting: 473 / 540
Generated images 0473 of 0540
predicting: 474 / 540
Generated images 0474 of 0540
predicting: 475 / 540
Generated images 0475 of 0540
predicting: 476 / 540
Generated images 0476 of 0540
predicting: 477 / 540
Generated images 0477 of 0540
predicting: 478 / 540
Generated images 0478 of 0540
predicting: 479 / 540
Generated images 0479 of 0540
predicting: 480 / 540
Generated images 0480 of 0540
predicting: 481 / 540
Generated images 0481 of 0540
predicting: 482 / 540
Generated images 0482 of 0540
predicting: 483 / 540
Generated images 0483 of 0540
predicting: 484 / 540
Generated images 0484 of 0540
predicting: 485 / 540
Generated images 0485 of 0540
predicting: 486 / 540
Generated im

In [19]:
import torch
print(torch.cuda.current_device())

0


In [29]:
!python3 evaluate/utils.py --gt_dir "../dataset/ISTD_Dataset/test/test_C" \
--est_dir "../generated_200_epoches/shadow_free" --img_suf ".png"\
2>&1 | tee ../evaluate_200_epoches.log

143it [00:32,  3.96it/s]gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.

429it [01:35,  5.31it/s]gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.shape: (480, 640, 3) est_img.shape: (480, 640, 3)
gt_img.

In [39]:
!python3 playground/blur_tf.py

2023-02-03 10:37:54.002177: I tensorflow/core/platform/cpu_feature_guard.cc:193] This TensorFlow binary is optimized with oneAPI Deep Neural Network Library (oneDNN) to use the following CPU instructions in performance-critical operations:  AVX2 AVX512F AVX512_VNNI FMA
To enable them in other operations, rebuild TensorFlow with the appropriate compiler flags.
2023-02-03 10:37:56.264140: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2023-02-03 10:37:57.276214: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] Could not load dynamic library 'libnvinfer.so.7'; dlerror: libnvinfer.so.7: cannot open shared object file: No such file or directory
2023-02-03 10:37:57.276300: W tensorflow/compiler/xla/stream_executor/platform/default/dso_loader.cc:64] 

In [53]:
!python3 loss_utils.py

[[[124. 124. 122.]
  [125. 126. 123.]
  [126. 128. 126.]
  ...
  [161. 183. 191.]
  [162. 178. 183.]
  [138. 142. 145.]]

 [[125. 125. 125.]
  [122. 122. 120.]
  [122. 123. 120.]
  ...
  [170. 194. 201.]
  [158. 172. 176.]
  [136. 136. 139.]]

 [[120. 120. 118.]
  [122. 123. 121.]
  [119. 121. 118.]
  ...
  [167. 193. 198.]
  [157. 167. 172.]
  [113. 110. 114.]]

 ...

 [[140. 141. 141.]
  [136. 136. 137.]
  [135. 136. 135.]
  ...
  [146. 139. 134.]
  [157. 149. 143.]
  [152. 143. 135.]]

 [[136. 137. 136.]
  [142. 143. 142.]
  [143. 143. 142.]
  ...
  [149. 143. 138.]
  [156. 148. 142.]
  [149. 140. 132.]]

 [[134. 135. 135.]
  [136. 138. 136.]
  [137. 138. 136.]
  ...
  [153. 146. 141.]
  [166. 158. 151.]
  [158. 149. 141.]]]
Kernel shape: torch.Size([3, 1, 21, 21])
tensor([[[[8.2882e-05, 1.2726e-04, 1.8677e-04,  ..., 1.8677e-04,
           1.2726e-04, 8.2882e-05],
          [1.2726e-04, 1.9540e-04, 2.8678e-04,  ..., 2.8678e-04,
           1.9540e-04, 1.2726e-04],
          [1.8677e-